export const cities = [
  { "id": "622", "cityName": "Agra" },
  { "id": "154", "cityName": "Ahmedabad" },
  { "id": "265", "cityName": "Bangalore Urban" },
  { "id": "571", "cityName": "Chennai" },
  { "id": "140", "cityName": "Delhi, New" },
  { "id": "149", "cityName": "Delhi, South" },
  { "id": "145", "cityName": "Delhi, East" },
  { "id": "142", "cityName": "Delhi, West" },
  { "id": "146", "cityName": "Delhi, North" },
  { "id": "307", "cityName": "Ernakulam, Kerala" },
  { "id": "651", "cityName": "Gaziabad" },
  { "id": "581", "cityName": "Hyderabad" },
  { "id": "544", "cityName": "Kanyakumari" },
  { "id": "725", "cityName": "Kolkotta" },
  { "id": "596", "cityName": "Medchal, Telangana" },
  { "id": "395", "cityName": "Mumbai" },
  { "id": "266", "cityName": "Mysore" },
  { "id": "650", "cityName": "Noida" },
  { "id": "308", "cityName": "Palakkad, Kerala" },
  { "id": "363", "cityName": "Pune" },
  { "id": "173", "cityName": "Rajkot, Gujarat" },
  { "id": "775", "cityName": "Rajkot Corporation, Gujarat" },
  { "id": "603", "cityName": "Ranga Reddy, Telangana" },
  { "id": "296", "cityName": "Thiruvananthapuram, Kerala" },
  { "id": "167", "cityName": "Valsad, Gujarat" }
];
